
platform :ios, '9.0'
use_frameworks!

target 'TB_Client_Buyer' do

pod 'Alamofire', '~> 3.0'

pod 'SwiftQRCode'

pod 'KeychainSwift', '~> 3.0'

pod 'Bluetonium'

pod 'FlatUIKit'

pod 'SSBouncyButton', '~> 1.0'


end

target 'TB_Client_BuyerTests' do

end

target 'TB_Client_BuyerUITests' do

end

