
platform :ios, '9.0'
use_frameworks!

target 'TB_Client_Buyer' do

pod 'Alamofire', '~> 3.0'

pod 'SwiftQRCode'

pod 'KeychainSwift', '~> 3.0'

pod 'Bluetonium'

#pod 'FBSDKCoreKit'

#pod 'FBSDKLoginKit'

pod 'BButton'

end

target 'TB_Client_BuyerTests' do

end

target 'TB_Client_BuyerUITests' do

end

