
platform :ios, '9.0'
use_frameworks!

target 'TB_Client_Buyer' do

pod 'Alamofire', '~> 3.0'

pod 'SwiftQRCode'

pod 'KeychainSwift', '~> 3.0'

pod 'Bluetonium'

pod 'BButton'

pod 'ObjectMapper', '~> 1.3'

pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

pod 'MBProgressHUD', '~> 0.9.2'

pod 'SCLAlertView'

pod 'AlamofireNetworkActivityIndicator', '~> 1.0'

end

target 'TB_Client_BuyerTests' do

end

target 'TB_Client_BuyerUITests' do

end

